symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    
    # Durée de validité du lien envoyé par mail (en secondes).
    lifetime: 3600

    # Temps minimum à attendre entre deux demandes (en secondes).
    # 10 min (default: 15)
    throttle_limit: 600